### PR TITLE
Add support for delta-source-fat-* directives

### LINKED ISSUE #201: Support delta-source-fat-offset and delta-source-fat-path
Delta upgrades do not support applying delta on FAT files, zImage on boot partition for many devices, precisely.

Supporting delta-source-fat-offset and delta-source-fat-path is needed for applying delta upgrades on FAT files.

### PR DESCRIPTION
**Pull request by jeanparpaillon**
Closes #201

### CODE REVIEW

**Comment by fhunleth** [comment]
Whoa!!! I didn't expect a PR. Thank you!!! 

I've been trying my best to finish off one OSS task on my plate before starting fwup work. Fwup is definitely next on my list, but I'm going to get the other one in a good spot to take a break from it today. This PR is too good. I need to get in it this weekend.

**Comment by jeanparpaillon** [comment]
@fhunleth glad you appreciate :) I really need to strip down OTA updates, and linux kernel is big, hence my PR.

**Comment by jeanparpaillon** [comment]
@fhunleth I've added a ticket for making NervesHub compatible https://github.com/nerves-hub/nerves_hub_web/issues/885

**Comment by jeanparpaillon** [comment]
...and this one for nerves' firmware.patch task  https://github.com/nerves-project/nerves/issues/856

**Comment by fhunleth** [comment]
@jeanparpaillon I rebased, updated it to work with xdelta bounds checking code that was added, and removed some code that wasn't needed. It's in `main` now. Thank you very much for submitting this. My plan is to look at a couple more fwup updates this week and then make a release. When you get a chance, could you check that `main` continues to work for you with my changes?

**Pull request closed without merging**
